# The server will be shutdown if this configuration is invalid, outdated, etc.

database:
  # These are the following supported databases: "POSTGRESQL".
  type:
  host:
  port:
  name:
  username:
  password:

# Do not change this value manually, it is used to give out of date warnings.
version: 0.0.1