# The server will be shutdown if this configuration is invalid, outdated, etc.

database:
  # These are the following supported databases: "POSTGRESQL".
  type:
  host:
  port:
  name:
  username:
  password:

permissions:
  # When ever a target is punished, a log message is announced to all that have these permissions.
  # Each permission applies to their respective initial punishments, and pardon punishments.
  # For example, view-player-mute-announces applies to a player getting muted and unmuted.
  announces:
    view-player-mute-announces: "nooniemanagement.view.mute.announces"
  commands:
    player-mute-command: "nooniemanagement.mute.player"
    player-unmute-command: "nooniemanagement.unmute.player"

duration-format:
  days:
    identifiers: ["d", "day", "days"]
    plural: "days"
    singular: "day"
  hours:
    identifiers: ["h", "hr", "hour", "hours"]
    plural: "hours"
    singular: "hour"
  minutes:
    identifiers: ["m", "min", "minute", "minutes"]
    plural: "minutes"
    singular: "minute"
  seconds:
    identifiers: ["s", "sec", "second", "seconds"]
    plural: "seconds"
    singular: "second"

messages:
  console-name: "[CONSOLE]"
  mute:
    player-mute: "{issuer} muted {target} for {duration}"
    player-permanent-mute: "{issuer} muted {target} permanently"
    player-unmute: "{issuer} unmuted {target}"
    player-already-muted: "{target} is already muted"
    player-not-muted: "{target} is not muted"

# Do not change this value manually, it is used to give out-of-date warnings.
version: 0.0.1