# The server will be shutdown if this configuration is invalid, outdated, etc.

# The name of the database will be "NoonieManagement".
database:
  # These are the following supported databases: "POSTGRESQL".
  type:
  username:
  password:
  host:
  port:

# Do not change this value manually, it is used to give out of date warnings.
version: 0.0.1